projet Projet PDB 2526
charger Charger
sauver Sauver
créer Créez...
inst.existePas Cette installation n'existe pas
inst.id Entrez l'id de l'installation

titre.piece.creer Création d'une Piece
piece.nom Nom
piece.description Description
piece.etage Etage
piece.typePiece Type de pièce
piece.titre Piece

piece.liste.titre Liste des pièces
operation Opération

implantation.titre Plan d'implantation

choix.quitter.sauver Quitter et Sauver
choix.quitter.pas.sauver Quitter sans sauver
choix.quitter Quitter
choix.annuler Revenir à l'application

end.confirm.titre Confirmation de la fermeture
end.confirm.info Vous êtes sur le point de quitter l'application
end.confirm.question Voulez-vous quitter l'application ?

installation Installation
app Appareil


ctx.addPiece Ajoute une pièce
ctx.delPiece Supprime une pièce

app.codes Codes autorisés
app.prise Prise
app.interrupteur Interrupteur
app.lampe Lampe
app.appareillage Appareillage
app.telerupteur Télérupteur
app.televariateur Télévariateur
app.transformateur Transformateur
app.bouton Bouton

conf.save Voulez-vous sauvez les modifications ?
conf.quitter.sans.sauver Voulez-vous quitter sans sauver les modifications?
conf.suppression Voulez-vous vraiment supprimer cet objet?
err.save Erreur lors de la sauvegarde
err.noInstall Pas d'installation chargée
err.install.inconnue Installation inconnue!
err.update La mise à jour n'a pas fonctionné
err.nbr Il faut entrer un nombre!
err.appareil.code.existe.pas Le code {0} n''existe pas pour l''objet {1}
err.suppression.impossible L'objet ne peut pas être supprimé car il a des dépendances 
err.insertion.impossible L'objet ne peut pas être sauvé car il référence un objet non présent
err.mise_a_jour.impossible La mise à jour ne peut pas se faire

bt.load Charger une Installation
bt.update Modifie l'installation
bt.save Sauve l'installation
bt.implantation Implantation

bt.liste.piece Liste des pièces
bt.cree.piece Ajouter une pièce 

bt.element Eléments
bt.associe.piece Associe à une pièce
bt.schema Schéma étage

action.ok  Valider
action.add  Ajout
action.maj  Mise à Jour
action.del  Supprimer
action.quitter  Quitter
action.save Sauver
action.check Vérification
action.reload Recharger

action.annuler  Annuler
action.charger  Charger
